import type { Metadata } from "next";
import { MuseoModerno, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

// Load MuseoModerno for headers
const museoModerno = MuseoModerno({
  subsets: ["latin"],
  variable: "--font-museo-moderno", // Define a CSS variable
  weight: ["400", "500", "700"], // Adjust weights as needed
});

// Load Red Hat Display for paragraphs
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat-display", // Define a CSS variable
  weight: ["400", "500", "700"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${museoModerno.variable} ${redHatDisplay.variable}`}
    >
      <body className="antialiased flex flex-col items-center ">
        <div className="w-[calc(100%-30px)] mt-4 flex flex-col items-center ">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
