import type { Metadata } from "next";
import { MuseoModerno, Red_Hat_Display } from "next/font/google";
import "./globals.css";

const museoModerno = MuseoModerno({
  subsets: ["latin"],
  variable: "--font-museo-moderno",
  weight: ["400", "500", "700"], // Adjust weights as needed
});

// Load Red Hat Display for paragraphs
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat-display",
  weight: ["400", "500", "700"], // Adjust weights as needed
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${museoModerno.variable} ${redHatDisplay.variable} antialiased`}
      >
        {/* navbar  */}
        {children}

        {/* footer */}
      </body>
    </html>
  );
}
